### PR TITLE
Hsdio waveform fix

### PR DESCRIPTION
**Pull request by JuanBohorquez3**
Fixed a round of issues having to do with HSDIO waveforms and scripting. Test on your machines to make sure this works.

### CODE REVIEW

**Review by prhuft — APPROVED** [review]

**Comment by JuanBohorquez3** [comment]
Currently hitting "update settings" more than once in cspy breaks the HSDIO. Looks like the server tries to initialize a new HSDIO card (rather than update the waveforms on the existing card).

**Comment by JuanBohorquez3** [comment]
Quitting the server after opening connection, but before hitting "update settings" soft locks the server. It tries to close the HSDIO connection but hangs at that point

**Comment by JuanBohorquez3** [comment]
When testing the Hamamatsu code I found that when another instrument is present, if the other instrument fails the PXI class will close the failing instrument then attempt to restart the server with the HSDIO still active. 

Currently the re-initialization fails because HSDIOsession.initiate is called while the HSDIO is in a running state. This is despite a call to the HSDIO.stop() function which should abort the process.

**Comment by prhuft** [comment]
> When testing the Hamamatsu code I found that when another instrument is present, if the other instrument fails the PXI class will close the failing instrument then attempt to restart the server with the HSDIO still active.

Did you actually mean when testing the Hamamatsu code?

**Comment by c-poole** [comment]
Both this and the other branch are experiencing measurement timeouts which I have been trying to diagnose but so far have not made headway on.

**Comment by JuanBohorquez3** [comment]
> Both this and the other branch are experiencing measurement timeouts which I have been trying to diagnose but so far have not made headway on.

Can you elaborate? When does the error message output look like? Where is the code failing?

**Comment by c-poole** [comment]
There isn't an error message. It just doesn't send information back to cspy so cspy times out. I'm putting in some logging to try and figure out why the measurement isn't completed to try and gather more info.

**Comment by c-poole** [comment]
Figured out that part of the issue was me not understanding the testing parameters and part was that my HSDIO settings are such that I wouldn't be able to tell if it was working even if it was. Both issues have been fixed so this LGTM.

**Review by c-poole — APPROVED** [review]

**Pull request merged**
