### PR TITLE
Cycle time when not cycling continuously

### PR DESCRIPTION
**Pull request by prhuft**
The cycle time when cycling continuously is disabled in CsPy is not dramatically longer anymore, compared to the old server. As a bonus, this PR adds the ability to export the most recently received xml experiment update message to a text file. Lastly, some of the verbose logging in TCP has been leveled down to debug. 

Resolves issue #36

### CODE REVIEW

**Comment by JuanBohorquez3** [comment]
Whenever the experiment cycles I get the following warning message.

'Finite acquisition or generation has been stopped before the requested number of samples were acquired or generated.
  warnings.warn(DaqWarning(
C:\Users\Hybrid\Envs\Instrument_Servers\lib\site-packages\nidaqmx\errors.py:140: DaqWarning:
Warning 200010 occurred.'

It occurs once per measurement cycle.

Looks like it's not being logged by a logger so I can't tell where it's coming from.

Strangely enough I don't seem to get the warning when the server is in debug mode.

Console output for reference:
image

**Comment by prhuft** [comment]
That's pretty weird. It's an issue with either AI, AO, or TTL stuff then. You know which of those you use so you can narrow it down. And just to be clear, this does not happen on the current master branch?

**Comment by JuanBohorquez3** [comment]
Another small thing. When "x" is pressed I get both the "Wrote XML to..." message and the "Not a valid key press..." message. Probably a quick fix.

**Comment by c-poole** [comment]
Add the file that gets generated for the pxi message to the gitignore

**Comment by prhuft** [comment]
> Another small thing. When "x" is pressed I get both the "Wrote XML to..." message and the "Not a valid key press..." message. Probably a quick fix.

this happens for any key press. it's like depressing an releasing a key might be read separately or something. i haven't investigated it yet.

**Comment by prhuft** [comment]
master merged in b/c juan (justifiably) afraid of losing hamamatsu changes

**Pull request merged**
