### PR TITLE
Data out

### PR DESCRIPTION
**Pull request by prhuft**
This PR adds methods such as is_done, start, stop, and data_out to the relevant device class (excluding hamamatsu and counters). Regions where these methods are called in pxi.py are no longer commented.

### CODE REVIEW

**Comment by prhuft** [comment]
@JuanBohorquez3 please check that hamamatsu.py agrees with what you have as the most up-to-date version in master.

**Comment by JuanBohorquez3** [comment]
I resolved the merge conflicts in hamamatsu.py, that file looks good now.
On github the entirety of pxi.py is being registered as a merge conflict making it hard to resolve.

**Comment by c-poole** [comment]
The pxi changes according to git all seem reasonable so we can resolve a full file conflict by just taking the new version.

**Review by JuanBohorquez3 — APPROVED** [review]
Looks good

**Pull request merged**
