### PR TITLE
TTL Input live test

### PR DESCRIPTION
**Pull request by prhuft**
TTL input module correctly measures data and sends it out in a way CsPy can understand. No known bugs during normal operation. Please test on your experiment. 

NOTE: This branch is based off of the aio_tests branch, which you should have already confirmed to be working before testing this.

### CODE REVIEW

**Review by c-poole — APPROVED** [review]
My experiment has TTL disabled so I can't really test to make sure this works but it also doesn't break my system so thumbs up from me,

**Comment by JuanBohorquez3** [comment]
image
Image taken of a miscellaneous cycle during the course of my cycle continuously loop. 
Looks like the TTL task is started, it's data is read out, then the task is stopped, three times in the course of one cycle.
Is this the expected behavior?

**Comment by JuanBohorquez3** [comment]
image
I also see this warning occur when I close the server with the q input.

**Comment by prhuft** [comment]
I also observe that the TTL check happens three times, which I thought had to do with my xml somehow, but now I doubt this. I'll investigate.

**Comment by prhuft** [comment]
1) The TTL input get called twice (which is the expected behavior), not three times now.
2) The shutdown is cleaner, but there is still a resource warning. Strangely, the problematic task seems to be the AnalogInput. Stranger still, it's only a problem when I have my TTL filters enabled. 

image

Strangest still, if i print the names of the tasks (which is how I figured out AI was the trouble-maker), the shutdown warning goes away entirely.  

image

For now, I am requesting that we merge this PR as is; the warning is fairly trivial and is not worth more debugging time right now.

**Pull request merged**
